### ISSUE TITLE
Option to use the previous theme colors

### ISSUE THREAD

**Issue by danieljpgo** [kettanaito/vscode-nako-theme#11]
It would be great to have a "classic" option, because the old theme was great and I would like to continue using it.

In case you're not interested, would it be cool to fork it?

**Comment by kettanaito** [comment]
Hey, @danieljpgo. Thanks for reaching out. 

More people contacted me since the latest release about having a possibility to use the previous version of the theme.

## How to use the previous theme?

1. Open your VS Code.
2. Install `nako` (see README).
3. Open command palette, choose "Extensions: Install Specific Version of Extension...":

<img width="742" alt="Screenshot 2022-08-05 at 11 33 44" src="https://user-images.githubusercontent.com/14984911/183049137-74bbaeab-5caa-405b-8e65-d6cf90c4d511.png">

4. In the prompt, choose "Nako".
5. In the prompt of versions, choose 0.1.5 (the latest 0.1.x version).
6. Enjoy.

**Comment by kettanaito** [comment]
You may also want to disable autoupdates for this extension so that VS Code doesn't automatically update you to the next version (although that'd be a semver breach, forcing a breaking change to the consumer; you never know).

**Comment by kettanaito** [comment]
## Released: v0.2.1 🎉

This has been released in v0.2.1!

- 📄 [**Release notes**](https://github.com/kettanaito/vscode-nako-theme/releases/tag/v0.2.1)
- 📦 [npm package](https://www.npmjs.com/package/nako/v/0.2.1)

Make sure to always update to the latest version (`npm i nako@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
